apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"datetime-app","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"datetime-app"}},"template":{"metadata":{"labels":{"app":"datetime-app"}},"spec":{"containers":[{"image":"ayushi0903/datetime-app:latest","name":"datetime-app","ports":[{"containerPort":8080}]}]}}}}
  creationTimestamp: "2025-03-20T18:27:00Z"
  generation: 1
  name: datetime-app
  namespace: default
  resourceVersion: "40243"
  uid: ce5adfba-4ea1-489f-b23f-38be52dfa3d1
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: datetime-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: datetime-app
    spec:
      containers:
      - image: ayushi0903/datetime-app:latest
        imagePullPolicy: Always
        name: datetime-app
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-03-20T18:27:11Z"
    lastUpdateTime: "2025-03-20T18:27:11Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-03-20T18:27:00Z"
    lastUpdateTime: "2025-03-20T18:27:11Z"
    message: ReplicaSet "datetime-app-7966f87596" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
