apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"datetime-app-service","namespace":"default"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":8080}],"selector":{"app":"datetime-app"},"type":"LoadBalancer"}}
  creationTimestamp: "2025-03-20T18:27:08Z"
  name: datetime-app-service
  namespace: default
  resourceVersion: "40231"
  uid: 886983de-2329-48e4-9778-b194f74ff5bd
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.101.211.168
  clusterIPs:
  - 10.101.211.168
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32329
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: datetime-app
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
